steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/ulejraai/cloud-run-source-deploy/ulejraai/frontend:$COMMIT_SHA'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/ulejraai/cloud-run-source-deploy/ulejraai/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
